### ISSUE TITLE
Morning Code Review

### ISSUE THREAD

**Issue by marcelosdata** [kemar-art/My-Portfolio#3]
Code Review on Morning session

**Comment by marcelosdata** [comment]
Your code is looking good. You are on the right track.

- Kindly set elements that share the same font family, font-size, font-color, etc; in the parent selector instead of the elements themselves 👍

**Comment by jpol01** [comment]
Nice job, I don't see anything to add (during the morning session, Kemar agreed to do some changes such as: to group some properties, making the code cleaner.)

**Comment by mrjuda** [comment]
Great job so far, keep it up!
